### ISSUE TITLE
Error con comillas en preprocesado?

### ISSUE THREAD

**Issue by aitorfi** [aitorfi/42_minishell#58]
Hay que probar si lo siguiente es un error:

![2024-01-28_12-46-50](https://github.com/aitorfi/42_minishell/assets/64830228/2c041b36-22ad-417f-aed9-70d534c4253d)

**Comment by Alvicina** [comment]
okey lo miro ahora

**Comment by Alvicina** [comment]
Corregido, tenia que meter una condicion en el trimeado y listo.

**Comment by Alvicina** [comment]
Lo he mergeado al master tambien
