### ISSUE TITLE
Exit_bug

### ISSUE THREAD

**Issue by Alvicina** [aitorfi/42_minishell#64]
<img width="368" alt="Screen Shot 2024-01-30 at 4 38 33 PM" src="https://github.com/aitorfi/42_minishell/assets/144911724/4c74e9d1-b362-4f70-80df-4e5b4f65870c">

Aitor me he fijado que cuando introducimos exi (sin la t) en el terminal, estamos ejecutando exit. Crees que se pueda deber al builtin?

**Comment by aitorfi** [comment]
Lo del exit concretamente está corregido, el error se producia porque al comparar el input del usuario "exi" con "exit" solo se comparaban los caracteres del input (solo se comparaban 3 caracteres) y entonces lo tratabamos como si hubiera introducido el comando exit.

**Código erroneo:**

```c
// Si cmd es igual a "c" ft_strncmp devuelve que son iguales
// porque len es igual a 1, solo compara el primer caracter.
len = ft_strlen(cmd);
ft_strncmp(cmd, "cd", len);
```

**Código corregido:**

```c
// Usando max_of (es una función nueva que he hecho en utils.c) 
// nos devuelve el numero mas grande de los dos enviados por parámetro
// y de esta forma siempre va a comparar por lo menos 2 caracteres.
len = ft_strlen(cmd);
ft_strncmp(cmd, "cd", max_of(len, 2));
```

**Comment by Alvicina** [comment]
Perfecto! gracias Aitor
